<x-church::website.layout pageName="Welcome">
<h4>Welcome to Westville Methodist Church!</h4>
If you have managed to join us for a service, we hope that you felt comfortable, that you managed to meet some people and that you had a real sense of encountering God in worship. We know how hard it is to find your way into a new church community but if you are keen to join us on a more regular basis, we'd love to make the experience easier for you! Here are some details that may help you to feel at home:<br><br>
<ul>
    <li>On Sundays <strong>after</strong> the 09h00 service, we serve tea and eats in the Supper Room (next to the ground floor kitchen, alongside the courtyard). In the 07h30 and 18h30 services tea is served <strong>before</strong> the service at the welcome counter inside the church. Somehow, meeting new people is a little easier with a cup in your hand - we'd love you to resist the urge to head for the parking lot and instead join us and meet more of the community :)</li>
    <li>If you have <strong>children</strong> worshipping with you, they are most welcome to stay in the service if you would prefer, but would probably be much happier joining one of the groups meeting during the 09h00 service :) Our youth meet in the upstairs Youth Room, Senior primary in the Upper Hall, Junior Primary in the Lower Hall, and the Creche in the Lounge (close to the main entrance to the sanctuary).</li>
    <li>When it comes to feeling like a part of the community, one of the best things you can do is get involved in a <strong>small group</strong> or a <strong>service team</strong> - this dramatically speeds up the process of getting to know people. There are pamphlets at the welcome counter at the back of the church with details of small groups and service teams (or contact the office if you need a hand).</li>
    <li>If you'd like to get in touch with our minister, Michael, you're welcome to set up a time to meet, either by contacting the office or by WhatsApping or calling him on 079 4999 139.</li>
    <li>Look out for our regular <strong>Newcomers Teas</strong> - an informal get-together after the 09h00 service that gives you a chance to meet some of us and find out more about the church.</li>
    <li>If you have a chance, explore our website or try out our <a href="https://app.westvillemethodist.co.za">app</a> for more info about WMC.</li>
    <li>We also have a WhatsApp group and email list that you may want to join for occasional announcements, daily devotions and the weekly <strong>Staying Connected newsletter</strong>. Let the office know (<a href="mailto:office@westvillemethodist.co.za">office@westvillemethodist.co.za</a>) if you'd like to be added.</li>
    <li>Please feel free to phone or come in and visit us in the church office (we are open from 08h30 till 14h00 every weekday, but close at 1pm on Fridays. You will meet Lauren and Ashley in the front office and, although Michael takes Mondays off, he's usually around during the rest of the week.</li>
</ul>
Please let us know if we can help in any other way at all. Hope to see you soon!
</x-church::layout>                
